name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting (bypass errors)
      run: npm run lint || true  # Se falhar, continua a pipeline
      
    - name: Build application
      run: npm run build
      
    - name: Build Docker image
      run: docker build -t aiagent-automate-frontend .
      
    - name: Run security scan (bypass errors)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'aiagent-automate-frontend:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
      continue-on-error: true  # Se encontrar vulnerabilidades, a esteira continua
